<a href="https://colab.research.google.com/github/akechsmith/ICS-2207-SCIENTIFIC-COMPUTING/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**
Is a multidimenssion arrays
numpy is used over List because it is faster

numpy used fixed type.

WHY FASTER:

*   Faster to read less bytes of menmory
*   No type checking when iterating through the objects
*   Numpy uses the contiguous memory -pointer

##### Differences betweeen List and Numpy
**List** <br>
a = [1,3,5] <br> b = [1,2,3]

a * b = error <br>
**NumPy** <br>

a = np.array([1,3,5]) <br>
b = np.array([1,2,3])

#### APPLICATION


*   Mathematics (MATLAB Replacement)
*   Plotting (Matplotlib)
*   Backend (Pandas , Correct4 Digital Photography)
*   Machine Learning



In [1]:
import numpy as np


In [2]:
# Initilalization

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 7.0, 5.0]])
print(b)

[[9. 8. 7.]
 [6. 7. 5.]]


In [4]:
#get the dimension

b.ndim

2

In [5]:
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int64')

In [7]:
#get the total size

In [8]:
a.nbytes

24

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
#get specifi element  [r,c]
a[1,5]

13

In [11]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
a[:,2]

array([ 3, 10])

In [13]:
#fancy [startindex,: endindex: stepsize]

a[0, 1: -1: 2]

array([2, 4, 6])

In [17]:
# insert
a[1,5] = 20


a[:,2] = 5

print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# **3D Example of Arrays**

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# get specific element (works outside in )
b[0,1,1]

4

In [25]:
#Replace
b[: ,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### TYPES OF ARRAYS



In [28]:
#All 0s matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
#All 1s matrix

np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [31]:
#Any number elements

np.full((2,2), 33)

array([[33, 33],
       [33, 33]])

In [34]:
#Random decimal number

np.random.rand(4,2)



array([[0.05885654, 0.77396498],
       [0.87279676, 0.68861573],
       [0.59547446, 0.09718464],
       [0.53051321, 0.29206494]])

In [35]:
#Random intergers
np.random.randint(7, size=(3,3))

array([[6, 2, 1],
       [2, 2, 0],
       [2, 2, 4]])

In [36]:
#Identity Matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
#Repeating array

arr = np.array([1,2,3])

r1 = np.repeat(arr, 3, axis=0)

print(r1)

[1 1 1 2 2 2 3 3 3]


In [46]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

output[1:-1,1:-1] = z

print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be Care when copying arrays**

### MATHEMATICAL PART

In [47]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [48]:
a + 2

array([3, 4, 5, 6])

In [49]:
a - 2

array([-1,  0,  1,  2])

In [50]:
a * 2

array([2, 4, 6, 8])

In [51]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [53]:
b =np.array([1,0,1,0])
print(b)

[1 0 1 0]


In [54]:
a + b

array([2, 2, 4, 4])

In [55]:
a ** 2

array([ 1,  4,  9, 16])

In [56]:
#Take on Sin

np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### LINEAR ALGEBRA

In [60]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [62]:
c = np.identity(3)
np.linalg.det(c)

1.0

### STATISTICS

In [63]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.min(stats)

1

In [68]:
np.max(stats, axis=1)

array([3, 6])

In [69]:
np.sum(stats, axis=0)

array([5, 7, 9])

### REORGANIZIGN ARRAYS


In [75]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [76]:
# vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### LOAD DATA

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')   #data.txt is the file name



#### BOOLEAN MASKING

In [77]:
v2 > 50

array([False, False, False, False])